### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by ipeacocks** [bzed/carbon-schema-to-clickhouse#1]
Hello.

Seems that smth is wrong with scheme converting. Let me show this on your README example:

```
[default]
pattern = .*
retentions = 1m:10d,15m:20d,30m:40d,60m:120d,360m:400d,720m:2y,1d:3y,7d:10y
```
```
<!-- default -->
	<default>
		<function>avg</function>
		<retention>
			<age>0</age>
			<precision>60</precision>
		</retention>
		<retention>
			<age>864000</age>
			<precision>900</precision>
		</retention>
		<retention>
			<age>1728000</age>
			<precision>1800</precision>
		</retention>
		<retention>
			<age>3456000</age>
			<precision>3600</precision>
		</retention>
		<retention>
			<age>10368000</age>
			<precision>21600</precision>
		</retention>
		<retention>
			<age>34560000</age>
			<precision>43200</precision>
		</retention>
		<retention>
			<age>63072000</age>
			<precision>86400</precision>
		</retention>
		<retention>
			<age>94608000</age>
			<precision>604800</precision>
		</retention>
	</default>
```

last value is `94608000` seconds and this is `1095 days` or `3 years`, not `10 years` as in your example. 

I would like to take this opportunity and ask about next xml part:
```
		<retention>
			<age>0</age>
			<precision>60</precision>
		</retention>
```
What does `<age>0</age>` mean? Why does `retentions = 1m:10d` mean `1m:0s`?

Thanks.

**Comment by ipeacocks** [comment]
Now I've got some ideas, it's kind of range of values: `0-864000` is first one etc. But how with such scheme to describe `10y` as latest duration?

**Comment by bzed** [comment]
Hi,

> last value is 94608000 seconds and this is 1095 days or 3 years, not 10 years as in your example.

That is correct. Clickhouse only reduces the precision by running an aggregate function, it never deletes data. You could only do this manually by deleting partitions. So the last precision is kept for ever. Or until your cronjobs deletes partitions.

```
<retention>
	<age>0</age>
	<precision>60</precision>
</retention>
```

This means, that the precision for new data is 60 seconds in this case. As soon as it is older than 864000s, the precision is reduced to 900s.

```
<retention>
	<age>864000</age>
	<precision>900</precision>
</retention>
```

Hope that explains it.

**Comment by ipeacocks** [comment]
Thanks. You've explained really well
